export default {
  appId: process.env.APP_ID,
  apiKey: process.env.API_KEY,
  indexPrefix: '',
  rateLimit: 8,
  maxUrls: 1000,
  startUrls: [
    'architecture',
    'lego-batman-sets',
    'boost',
    'brickheadz',
    'brik-sketches',
    'city',
    'classic',
    'creator-3-in-1',
    'creator-expert',
    'dc',
    'disney',
    'mickey-mouse',
    'dots',
    'duplo',
    'friends',
    'disney-frozen-2',
    'harry-potter',
    'ideas',
    'jurassic-world',
    'art',
    'lego-education',
    'super-mario',
    'marvel',
    'mindstorms',
    'minecraft',
    'minifigures',
    'minions',
    'monkie-kid',
    'ninjago',
    'power-functions',
    'powered-up',
    'serious-play',
    'speed-champions',
    'lego-spider-man',
    'star-wars',
    'stranger-things',
    'technic',
    'trolls',
    'vidiyo',
    'xtra',
  ].map(category => `https://www.lego.com/en-it/themes/${category}`),
  saveBackup: true,
  ignoreQueryParams: ['source', 'utm_*'],
  actions: [
    {
      indexName: 'lego_sets',
      pathsToMatch: ['https://www.lego.com/en-it/product/**'],
      recordExtractor: ({ $ }) => [
        {
          objectID: $('meta[property="product:retailer_item_id"]').attr('content'),
          name: $('h1[data-test="product-overview-name"]').text(),
          description: $('meta[name=description]').attr('content'),
          image: $('meta[property="og:image"]').attr('content').split('?')[0],
          url: $('meta[property="og:url"]').attr('content'),
          rating: parseFloat($('div.RatingBarstyles__RatingContainer-sc-11ujyfe-2').attr('title')),
          availability: $('meta[property="product:availability"]').attr('content'),
          price: parseFloat($('meta[property="product:price:amount"]').attr('content')),
          currency: $('meta[property="product:price:currency"]').attr('content'),
          age: parseInt($('span[data-test="product-details__ages"]').text().replaceAll('+', ''), 10),
          pieces: parseInt($('span[data-test="product-details__piece-count"]').text(), 10),
          vipPoints: parseInt($('span[data-test="product-details__vip-points"]').text(), 10),
          theme: {
            name: $('.ProductOverviewstyles__BrandLink-sc-1a1az6h-6 span').text(),
            url: $('.ProductOverviewstyles__BrandLink-sc-1a1az6h-6').attr('href'),
            logo: $('.ProductOverviewstyles__BrandLink-sc-1a1az6h-6 img').attr('src'),
          },
          categories: $('.ShopMoreLikeThisstyles__StyledProductTag-wn4mf8-2').map(el => el.text()),
        },
      ],
    },
  ],
  initialIndexSettings: {
    'lego_sets': { // eslint-disable-line prettier/prettier
      searchableAttributes: ['unordered(title)', 'unordered(description)'],
      customRanking: ['desc(rating)', 'asc(price)'],
      attributesForFaceting: ['fileType', 'type'],
    },
  },
}
